### ISSUE TITLE
Sort tournaments reverse chronologically on the tournament page

### ISSUE THREAD

**Issue by punchagan** [india-ultimate/hub#118]
Currently live or the most recent tournaments should be shown before older tournaments

**Comment by SibiAkkash** [comment]
Hi @punchagan, is there any test data that we can use for the dev environment ? Is there test data already provided in this repo ? If so, please point me to it, i'm unable to find it ;)
Should i create manually add  test `Events` and `Tournaments` to check ?

**Comment by Joe2k** [comment]
Will pickup #116 and update here when raised the PR

**Comment by SibiAkkash** [comment]
> Will pickup #116 and update here when raised the PR

Thanks @Joe2k !

**Comment by AnishKacham** [comment]
Hey. I know this issue is closed but I think it will be better if we sort by start date instead, reasons:
1. I think people tend to think about the start date of an event more than it's end date.
2. In the case where there are two simultaneous tournaments happening (T1, T2) and T1 starting earlier and ending later than T2,
T2 would appear before T1
but I feel this will be a little surprising to the end user.
Shouldn't T1 appear before T2.

**Comment by SibiAkkash** [comment]
> Hey. I know this issue is closed but I think it will be better if we sort by start date instead, reasons:
> 
> 1. I think people tend to think about the start date of an event more than it's end date.
> 2. In the case where there are two simultaneous tournaments happening (T1, T2) and T1 starting earlier and ending later than T2,
>    T2 would appear before T1
>    but I feel this will be a little surprising to the end user.
>    Shouldn't T1 appear before T2.
>    @punchagan @SibiAkkash

We are sorting in descending order of end date, so if T1 ends later than T2, T1 will appear before T2 right ?

**Comment by AnishKacham** [comment]
> We are sorting in descending order of end date, so if T1 ends later than T2, T1 will appear before T2 right ?
Descending order is latest first, so shouldn't T2 appear before T1 because it started later? 🤔

**Comment by SibiAkkash** [comment]
> > We are sorting in descending order of end date, so if T1 ends later than T2, T1 will appear before T2 right ?\
> 
> Descending order is latest first, so shouldn't T2 appear before T1 because it started later? 🤔

Hmm, you're saying that the "most recent" tournament is the one that started last. 

Suppose T1 (start = 12th Oct, end = 15th Oct), T2 (start = 13th, end = 14th). 
Say we sort in descending order of start date.
On 13th Oct, T2 would appear before T1. On the 15th, T2 would be completed, but T1 would still be live. But because we sorted by descending order of start date, T2 would appear before T1, even though T1 is currently live.

What you're saying makes sense, i think we'd have to account for start date + whether a tournament is live or not ? Does that make sense ?

**Comment by AnishKacham** [comment]
> What you're saying makes sense, i think we'd have to account for start date + whether a tournament is live or not ? Does that make sense ?

Yess. Touché.
So instead of tossing around start and end dates we could just pin tournaments that are "live" to the top and sort the remaining by start date?

**Comment by SibiAkkash** [comment]
> > What you're saying makes sense, i think we'd have to account for start date + whether a tournament is live or not ? Does that make sense ?
> 
> Yess. Touché. So instead of tossing around start and end dates we could just pin tournaments that are "live" to the top and sort the remaining by start date?

We could change the api to return tournaments in descending order of start date, and do a sort on the frontend to show the live tournaments first. The sort would effectively pin most recent / latest live tournament to the start. Thoughts @punchagan ?

**Comment by Joe2k** [comment]
Yep last solution looks correct to me

**Comment by punchagan** [comment]
Excellent discussion, @AnishKacham 

I did wonder about this while merging the PR, but given how tournaments are organised in India currently, I felt putting too much effort into optimising this wasn't required. 

I guess sorting by start and end dates in the API, and special casing live events in the frontend should be good.

**Comment by SibiAkkash** [comment]
Alright, I'll change this, thanks @AnishKacham !
